# https://www.viget.com/articles/host-build-and-deploy-next-js-projects-on-github-pages/
name: Node.js CI

on:
	push:
		branches: [ main ]

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
			- uses: actions/checkout@v2

			- uses: actions/setup-node@v2
				with:
					# update the Node version to meet your needs
					node-version: 16
					cache: npm

			- name: Build
				run: |
					npm ci
					npm run build
					touch out/.nojekyll
					# configure the build here

			- name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.4.0 
        with:
          branch: gh-pages
          folder: out
